"""initial migration

Revision ID: 013a04962533
Revises: 
Create Date: 2021-02-28 20:47:43.512163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013a04962533'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('lat', sa.String(length=50), nullable=False),
    sa.Column('long', sa.String(length=50), nullable=False),
    sa.Column('percentage_full', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tanks')
    # ### end Alembic commands ###
